import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../ui/accordion";
import { Plus } from "lucide-react";

const faqdata = [
  {
    question: "What types of data can I analyze with your platform?",
    answer:
      "Our platform supports a wide range of data types, including user behavior, sales metrics, website traffic, and custom data from integrated sources.",
  },
  {
    question: "How secure is my data with your analytics platform?",
    answer:
      "We prioritize your data’s security by using industry-standard encryption and regular audits to ensure your information is always protected.",
  },
  {
    question: "Can I customize the reports generated by your platform?",
    answer:
      "Yes! Our platform allows you to fully customize your reports, providing the flexibility to focus on the metrics that matter most to your business.",
  },
  {
    question: "Do I need any technical skills to use the platform?",
    answer:
      "No technical skills are required! Our platform is designed to be user-friendly with an intuitive interface, making it accessible for everyone, regardless of technical background.",
  },
  {
    question: "How do I integrate your platform with my existing tools?",
    answer:
      "We offer easy-to-use integrations with various platforms such as Google Analytics, CRM tools, and more, to ensure smooth data syncing with your existing setup.",
  },
];

const FAQ = () => {
  return (
    <section className="py-20 sm:px-6" id="faq">
      <div className="container max-w-7xl mx-auto flex flex-col items-start gap-10 md:flex-row">
        <div className="flex  flex-col gap-3 items-start">
          <div className="flex  flex-col gap-2">
            <span className="font-bold text-main">Faq</span>
            <h2 className="text-3xl font-semibold tracking-tight sm:text-5xl">
              Frequently Asked Questions
            </h2>
          </div>
        </div>

        <Accordion
          type="single"
          collapsible
          className="w-full max-w-3xl flex flex-col gap-4"
        >
          {faqdata.map((item, index) => (
            <AccordionItem value={item.question} key={index}>
              <AccordionTrigger className="text-left text-lg  hover:no-underline [&>svg]:hidden font-semibold [&[data-state=open]>div>svg>path:first-child]:rotate-90 gap-3">
                {item.question}
                <div className="size-10 rounded-[0.5rem] flex items-center justify-center shrink-0">
                  <Plus className="size-6 text-muted-foreground" />
                </div>
              </AccordionTrigger>
              <AccordionContent className="text-lg text-muted-foreground">
                {item.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};

export default FAQ;
