import { InvoiceTableType, ProductsTableType } from "@/types/types";

export const InvoicesData: InvoiceTableType[] = [
  {
    id: 1,
    customer: "Ravi Kumar",
    date: "2025-05-20",
    brand: "Samsung",
    quantity: 2,
    amount: 48000,
    status: "Full-Paid",
    product: {
      id: "prd001",
      image: "/stock.png",
      name: "Galaxy A54",
      category: "Smartphone",
    },
    mobile: "9876543210",
    payment: "UPI",
    gstBill: true,
  },
  {
    id: 2,
    customer: "Anjali Mehta",
    date: "2025-05-18",
    brand: "Apple",
    quantity: 1,
    amount: 75000,
    status: "Credited",
    product: {
      id: "prd002",
      image: "/stock.png",
      name: "iPhone 14",
      category: "Smartphone",
    },
    mobile: "9123456780",
    payment: "Bank",
    gstBill: false,
  },
  {
    id: 3,
    customer: "Mohit Sharma",
    date: "2025-05-15",
    brand: "Sony",
    quantity: 3,
    amount: 36000,
    status: "Not-Paid",
    product: {
      id: "prd003",
      image: "/stock.png",
      name: "Sony WH-1000XM4",
      category: "Headphones",
    },
    mobile: "9812345678",
    payment: "Cash",
    gstBill: true,
  },
  {
    id: 4,
    customer: "Sneha Agarwal",
    date: "2025-05-10",
    brand: "HP",
    quantity: 1,
    amount: 65000,
    status: "Full-Paid",
    product: {
      id: "prd004",
      image: "/stock.png",
      name: "HP Pavilion 15",
      category: "Laptop",
    },
    mobile: "9988776655",
    payment: "UPI",
    gstBill: true,
  },
  {
    id: 5,
    customer: "Amit Joshi",
    date: "2025-05-08",
    brand: "Lenovo",
    quantity: 2,
    amount: 88000,
    status: "Credited",
    product: {
      id: "prd005",
      image: "/stock.png",
      name: "Lenovo ThinkPad X1",
      category: "Laptop",
    },
    mobile: "9001122334",
    payment: "Bank",
    gstBill: false,
  },
  {
    id: 6,
    customer: "Anjali Mehta",
    date: "2025-05-18",
    brand: "Apple",
    quantity: 1,
    amount: 75000,
    status: "Credited",
    product: {
      id: "prd002",
      image: "/stock.png",
      name: "iPhone 14",
      category: "Smartphone",
    },
    mobile: "9123456780",
    payment: "Bank",
    gstBill: false,
  },
];

export const ProductsData: ProductsTableType[] = [
  {
    id: 1,
    name: "Amaron Car Battery",
    price: 4500,
    stock: 20,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 90000,
    status: "Available",
  },
  {
    id: 2,
    name: "Exide Inverter Battery",
    price: 5200,
    stock: 8,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-21",
    brand: "Exide",
    totalValue: 41600,
    status: "LowStock",
  },
  {
    id: 3,
    name: "Bosch Power Drill",
    price: 3200,
    stock: 0,
    image: "/stock.png",
    category: "Tools",
    lastUpdated: "2025-05-18",
    brand: "Bosch",
    totalValue: 0,
    status: "Unavailable",
  },
  {
    id: 4,
    name: "Amaron Tubular Battery",
    price: 6000,
    stock: 5,
    image: "/stock.png",
    category: "Home",
    lastUpdated: "2025-05-22",
    brand: "Amaron",
    totalValue: 30000,
    status: "LowStock",
  },
  {
    id: 5,
    name: "Exide Bike Battery",
    price: 1800,
    stock: 15,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Exide",
    totalValue: 27000,
    status: "Available",
  },
  {
    id: 6,
    name: "Luminous Inverter Battery",
    price: 5000,
    stock: 10,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-23",
    brand: "Luminous",
    totalValue: 50000,
    status: "Available",
  },
  {
    id: 7,
    name: "V-Guard Voltage Stabilizer",
    price: 2600,
    stock: 7,
    image: "/stock.png",
    category: "Home Appliances",
    lastUpdated: "2025-05-21",
    brand: "V-Guard",
    totalValue: 18200,
    status: "LowStock",
  },
  {
    id: 8,
    name: "Exide Solar Battery",
    price: 6500,
    stock: 12,
    image: "/stock.png",
    category: "Renewables",
    lastUpdated: "2025-05-20",
    brand: "Exide",
    totalValue: 78000,
    status: "Available",
  },
  {
    id: 9,
    name: "Amaron Go Battery",
    price: 4000,
    stock: 0,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-19",
    brand: "Amaron",
    totalValue: 0,
    status: "Unavailable",
  },
  {
    id: 10,
    name: "SF Sonic Car Battery",
    price: 4300,
    stock: 14,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "SF Sonic",
    totalValue: 60200,
    status: "Available",
  },
  {
    id: 11,
    name: "Microtek Inverter",
    price: 4800,
    stock: 6,
    image: "/stock.png",
    category: "Home",
    lastUpdated: "2025-05-21",
    brand: "Microtek",
    totalValue: 28800,
    status: "LowStock",
  },
  {
    id: 12,
    name: "Amaron Tall Tubular",
    price: 7000,
    stock: 11,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 77000,
    status: "Available",
  },
  {
    id: 13,
    name: "Exide Matrix Red",
    price: 4900,
    stock: 9,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-23",
    brand: "Exide",
    totalValue: 44100,
    status: "LowStock",
  },
  {
    id: 14,
    name: "Luminous Solar Panel",
    price: 9500,
    stock: 4,
    image: "/stock.png",
    category: "Renewables",
    lastUpdated: "2025-05-22",
    brand: "Luminous",
    totalValue: 38000,
    status: "LowStock",
  },
  {
    id: 15,
    name: "Amaron Quanta Battery",
    price: 8500,
    stock: 16,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-21",
    brand: "Amaron",
    totalValue: 136000,
    status: "Available",
  },
  {
    id: 16,
    name: "Exide Mileage Battery",
    price: 3900,
    stock: 2,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Exide",
    totalValue: 7800,
    status: "LowStock",
  },
  {
    id: 17,
    name: "Amaron Hi-Life Pro",
    price: 4300,
    stock: 0,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 0,
    status: "Unavailable",
  },
  {
    id: 18,
    name: "Exide Eko Battery",
    price: 3700,
    stock: 10,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-21",
    brand: "Exide",
    totalValue: 37000,
    status: "Available",
  },
  {
    id: 19,
    name: "Amaron Fresh Battery",
    price: 3000,
    stock: 3,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 9000,
    status: "LowStock",
  },
  {
    id: 20,
    name: "V-Guard Inverter",
    price: 5200,
    stock: 13,
    image: "/stock.png",
    category: "Home",
    lastUpdated: "2025-05-22",
    brand: "V-Guard",
    totalValue: 67600,
    status: "Available",
  },
];
