import type {
  BranchesType,
  FullInvoiceTableType,
  InvoiceTableType,
  PricingDataType,
  ProductsTableType,
} from "@/types/types";

export const InvoicesData: InvoiceTableType[] = [
  {
    id: 1,
    customer: "Ravi Kumar",
    date: "2025-05-20",
    brand: "Samsung",
    quantity: 2,
    amount: 48000,
    status: "Full-Paid",
    product: {
      id: "prd001",
      image: "/stock.png",
      name: "Galaxy A54",
      category: "Smartphone",
    },
    mobile: "9876543210",
    payment: "UPI",
    gstBill: true,
  },
  {
    id: 2,
    customer: "Anjali Mehta",
    date: "2025-05-18",
    brand: "Apple",
    quantity: 1,
    amount: 75000,
    status: "Credited",
    product: {
      id: "prd002",
      image: "/stock.png",
      name: "iPhone 14",
      category: "Smartphone",
    },
    mobile: "9123456780",
    payment: "Bank",
    gstBill: false,
  },
  {
    id: 3,
    customer: "Mohit Sharma",
    date: "2025-05-15",
    brand: "Sony",
    quantity: 3,
    amount: 36000,
    status: "Not-Paid",
    product: {
      id: "prd003",
      image: "/stock.png",
      name: "Sony WH-1000XM4",
      category: "Headphones",
    },
    mobile: "9812345678",
    payment: "Cash",
    gstBill: true,
  },
  {
    id: 4,
    customer: "Sneha Agarwal",
    date: "2025-05-10",
    brand: "HP",
    quantity: 1,
    amount: 65000,
    status: "Full-Paid",
    product: {
      id: "prd004",
      image: "/stock.png",
      name: "HP Pavilion 15",
      category: "Laptop",
    },
    mobile: "9988776655",
    payment: "UPI",
    gstBill: true,
  },
  {
    id: 5,
    customer: "Amit Joshi",
    date: "2025-05-08",
    brand: "Lenovo",
    quantity: 2,
    amount: 88000,
    status: "Credited",
    product: {
      id: "prd005",
      image: "/stock.png",
      name: "Lenovo ThinkPad X1",
      category: "Laptop",
    },
    mobile: "9001122334",
    payment: "Bank",
    gstBill: false,
  },
  {
    id: 6,
    customer: "Anjali Mehta",
    date: "2025-05-18",
    brand: "Apple",
    quantity: 1,
    amount: 75000,
    status: "Credited",
    product: {
      id: "prd002",
      image: "/stock.png",
      name: "iPhone 14",
      category: "Smartphone",
    },
    mobile: "9123456780",
    payment: "Bank",
    gstBill: false,
  },
];

export const ProductsData: ProductsTableType[] = [
  {
    id: 1,
    name: "Amaron Car Battery",
    price: 4500,
    stock: 20,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 90000,
    status: "Available",
  },
  {
    id: 2,
    name: "Exide Inverter Battery",
    price: 5200,
    stock: 8,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-21",
    brand: "Exide",
    totalValue: 41600,
    status: "LowStock",
  },
  {
    id: 3,
    name: "Bosch Power Drill",
    price: 3200,
    stock: 0,
    image: "/stock.png",
    category: "Tools",
    lastUpdated: "2025-05-18",
    brand: "Bosch",
    totalValue: 0,
    status: "Unavailable",
  },
  {
    id: 4,
    name: "Amaron Tubular Battery",
    price: 6000,
    stock: 5,
    image: "/stock.png",
    category: "Home",
    lastUpdated: "2025-05-22",
    brand: "Amaron",
    totalValue: 30000,
    status: "LowStock",
  },
  {
    id: 5,
    name: "Exide Bike Battery",
    price: 1800,
    stock: 15,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Exide",
    totalValue: 27000,
    status: "Available",
  },
  {
    id: 6,
    name: "Luminous Inverter Battery",
    price: 5000,
    stock: 10,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-23",
    brand: "Luminous",
    totalValue: 50000,
    status: "Available",
  },
  {
    id: 7,
    name: "V-Guard Voltage Stabilizer",
    price: 2600,
    stock: 7,
    image: "/stock.png",
    category: "Home Appliances",
    lastUpdated: "2025-05-21",
    brand: "V-Guard",
    totalValue: 18200,
    status: "LowStock",
  },
  {
    id: 8,
    name: "Exide Solar Battery",
    price: 6500,
    stock: 12,
    image: "/stock.png",
    category: "Renewables",
    lastUpdated: "2025-05-20",
    brand: "Exide",
    totalValue: 78000,
    status: "Available",
  },
  {
    id: 9,
    name: "Amaron Go Battery",
    price: 4000,
    stock: 0,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-19",
    brand: "Amaron",
    totalValue: 0,
    status: "Unavailable",
  },
  {
    id: 10,
    name: "SF Sonic Car Battery",
    price: 4300,
    stock: 14,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "SF Sonic",
    totalValue: 60200,
    status: "Available",
  },
  {
    id: 11,
    name: "Microtek Inverter",
    price: 4800,
    stock: 6,
    image: "/stock.png",
    category: "Home",
    lastUpdated: "2025-05-21",
    brand: "Microtek",
    totalValue: 28800,
    status: "LowStock",
  },
  {
    id: 12,
    name: "Amaron Tall Tubular",
    price: 7000,
    stock: 11,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 77000,
    status: "Available",
  },
  {
    id: 13,
    name: "Exide Matrix Red",
    price: 4900,
    stock: 9,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-23",
    brand: "Exide",
    totalValue: 44100,
    status: "LowStock",
  },
  {
    id: 14,
    name: "Luminous Solar Panel",
    price: 9500,
    stock: 4,
    image: "/stock.png",
    category: "Renewables",
    lastUpdated: "2025-05-22",
    brand: "Luminous",
    totalValue: 38000,
    status: "LowStock",
  },
  {
    id: 15,
    name: "Amaron Quanta Battery",
    price: 8500,
    stock: 16,
    image: "/stock.png",
    category: "Electronics",
    lastUpdated: "2025-05-21",
    brand: "Amaron",
    totalValue: 136000,
    status: "Available",
  },
  {
    id: 16,
    name: "Exide Mileage Battery",
    price: 3900,
    stock: 2,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Exide",
    totalValue: 7800,
    status: "LowStock",
  },
  {
    id: 17,
    name: "Amaron Hi-Life Pro",
    price: 4300,
    stock: 0,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 0,
    status: "Unavailable",
  },
  {
    id: 18,
    name: "Exide Eko Battery",
    price: 3700,
    stock: 10,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-21",
    brand: "Exide",
    totalValue: 37000,
    status: "Available",
  },
  {
    id: 19,
    name: "Amaron Fresh Battery",
    price: 3000,
    stock: 3,
    image: "/stock.png",
    category: "Automotive",
    lastUpdated: "2025-05-20",
    brand: "Amaron",
    totalValue: 9000,
    status: "LowStock",
  },
  {
    id: 20,
    name: "V-Guard Inverter",
    price: 5200,
    stock: 13,
    image: "/stock.png",
    category: "Home",
    lastUpdated: "2025-05-22",
    brand: "V-Guard",
    totalValue: 67600,
    status: "Available",
  },
];

export const mockInvoices: FullInvoiceTableType[] = [
  {
    id: "1",
    date: "2025-05-01",
    customer: {
      name: "Arjun Mehta",
      mobile: "9876543210",
      address: "123, MG Road, Mumbai",
    },
    quantity: 3,
    amount: 4500,
    payment: "UPI",
    gstBill: true,
    status: "Full-Paid",
    products: [
      {
        id: "p001",
        image: "/stock.png",
        name: "Bluetooth Speaker",
        category: "Electronics",
        brand: "JBL",
        price: 1500,
        quantity: 3,
        sellingPrice: 1500,
        totalValue: 4500,
      },
      {
        id: "p002",
        image: "/stock.png",
        name: "Alexa Amazon",
        category: "Electronics",
        brand: "JBL",
        price: 1400,
        quantity: 5,
        sellingPrice: 1200,
        totalValue: 6000,
      },
    ],
    discount: 0,
  },
  {
    id: "2",
    date: "2025-05-03",
    customer: {
      name: "Sneha Kapoor",
      mobile: "9898989898",
      address: "C-204, Green Residency, Pune",
    },
    quantity: 2,
    amount: 3000,
    payment: "Cash",
    gstBill: false,
    status: "Credited",
    products: [
      {
        id: "p002",
        image: "/stock.png",
        name: "Running Shoes",
        category: "Footwear",
        brand: "Nike",
        price: 2000,
        quantity: 2,
        sellingPrice: 1500,
        totalValue: 3000,
      },
    ],
    discount: 1000,
  },
  {
    id: "3",
    date: "2025-04-25",
    customer: {
      name: "Ravi Shankar",
      mobile: "9123456780",
      address: "44B, Anna Nagar, Chennai",
    },
    quantity: 5,
    amount: 7500,
    payment: "Bank",
    gstBill: true,
    status: "Full-Paid",
    products: [
      {
        id: "p003",
        image: "/stock.png",
        name: "LED Tube Light",
        category: "Home Appliances",
        brand: "Philips",
        price: 1500,
        quantity: 5,
        sellingPrice: 1500,
        totalValue: 7500,
      },
    ],
  },
  {
    id: "4",
    date: "2025-04-28",
    customer: {
      name: "Neha Verma",
      mobile: "9876541230",
      address: "5th Block, Sector 62, Noida",
    },
    quantity: 1,
    amount: 45000,
    payment: "Bank",
    gstBill: true,
    status: "Not-Paid",
    products: [
      {
        id: "p004",
        image: "/stock.png",
        name: "Smartphone",
        category: "Electronics",
        brand: "OnePlus",
        price: 48000,
        quantity: 1,
        sellingPrice: 45000,
        totalValue: 45000,
      },
    ],
    oldItemDiscount: 3000,
  },
  {
    id: "5",
    date: "2025-05-06",
    customer: {
      name: "Kunal Roy",
      mobile: "9988776655",
      address: "Salt Lake, Kolkata",
    },
    quantity: 2,
    amount: 2600,
    payment: "UPI",
    gstBill: false,
    status: "Full-Paid",
    products: [
      {
        id: "p005",
        image: "/stock.png",
        name: "Wrist Watch",
        category: "Accessories",
        brand: "Titan",
        price: 1300,
        quantity: 2,
        sellingPrice: 1300,
        totalValue: 2600,
      },
    ],
  },

  // Additional 15 mock entries with string IDs
  ...Array.from({ length: 15 }, (_, i) => {
    const invoiceId = (6 + i).toString();
    const productId = `pid${6 + i}`;
    const quantity = (i % 4) + 1;
    const amount = 1000 * quantity;
    const gstBill = i % 2 === 0;
    const status = ["Full-Paid", "Credited", "Not-Paid"][i % 3] as
      | "Full-Paid"
      | "Credited"
      | "Not-Paid";
    const payment = ["UPI", "Cash", "Bank"][i % 3] as "UPI" | "Cash" | "Bank";

    return {
      id: invoiceId,
      date: `2025-05-${(7 + i).toString().padStart(2, "0")}`,
      customer: {
        name: `Customer ${i + 1}`,
        mobile: `90000000${(10 + i).toString().padStart(2, "0")}`,
        address: `Address ${i + 1}, India`,
      },
      quantity,
      amount,
      payment,
      gstBill,
      status,
      products: [
        {
          id: productId,
          image: "/stock.png",
          name: `Product ${i + 1}`,
          category: ["Gadgets", "Furniture", "Clothing"][i % 3],
          brand: ["Samsung", "Ikea", "Zara"][i % 3],
          price: amount,
          quantity,
          sellingPrice: amount,
          totalValue: amount,
        },
      ],
      ...(i % 2 === 0 ? { discount: 200 } : {}),
      ...(i % 4 === 0 ? { oldItemDiscount: 500 } : {}),
    };
  }),
];

export const mockBranches: BranchesType[] = [
  {
    id: "branch_001",
    branchName: "Downtown HQ",
    branchAddress: "123 Main Street, New York, NY 10001",
    branchImage: "/features.png",
    createdAt: "2025-05-01T10:30:00Z",

    isPrimaryBranch: true,
  },
  {
    id: "branch_002",
    branchName: "Westside Office",
    branchAddress: "456 Sunset Blvd, Los Angeles, CA 90028",
    branchImage: "/features.png",
    createdAt: "2025-04-25T14:00:00Z",

    isPrimaryBranch: false,
  },
  {
    id: "branch_003",
    branchName: "Midtown Center",
    branchAddress: "789 Broadway, Chicago, IL 60610",
    branchImage: "/features.png",
    createdAt: "2025-03-15T09:15:00Z",

    isPrimaryBranch: false,
  },
  {
    id: "branch_004",
    branchName: "Tech Hub",
    branchAddress: "101 Silicon Avenue, San Jose, CA 95110",
    branchImage: "/features.png",
    createdAt: "2025-02-20T13:45:00Z",

    isPrimaryBranch: false,
  },
  {
    id: "branch_005",
    branchName: "East Bay Office",
    branchAddress: "202 Lakeside Dr, Oakland, CA 94612",
    branchImage: "/features.png",
    createdAt: "2025-01-10T11:20:00Z",

    isPrimaryBranch: false,
  },
];

export const pricingData: PricingDataType[] = [
  {
    name: "Free",
    description:
      "For personal projects, startups or low-traffic basic websites.",
    price: 19,
    isMostPopular: false,
    features: [
      "Unlimited projects",
      "Unlimited storage",
      "24/7 support",
      "API access",
      "Custom branding",
    ],
    paymentLink: "https://buy.stripe.com/test_9AQg1X12keqzf2UfYZ",
    priceId: "price_1RL38ZPZo4NGp7MuqlyNLLVO",
  },
  {
    name: "Basic",
    description:
      "For fast growing startups and modern collaborative product teams.",
    price: 49,
    isMostPopular: true,
    features: [
      "Everything in Basic",
      "Priority support",
      "Advanced insights",
      "Custom monthly reports",
      "API Access",
    ],
    paymentLink: "https://buy.stripe.com/test_9AQg1X12keqzf2UfYZ",
    priceId: "price_1RL38ZPZo4NGp7MuqlyNLLVO",
  },
  {
    name: "Pro",
    description:
      "For big companies and enterprises with high traffic and custom needs.",
    price: 99,
    isMostPopular: false,
    features: [
      "Everything in Pro",
      "Single sign-on",
      "Custom SLA",
      "Custom integrations",
      "Custom reporting",
    ],
    paymentLink: "https://buy.stripe.com/test_9AQg1X12keqzf2UfYZ",
    priceId: "price_1RL38ZPZo4NGp7MuqlyNLLVO",
  },
];
