import { InvoiceTableType } from "@/types/types";

export const InvoicesData: InvoiceTableType[] = [
  {
    id: 1,
    customer: "Ravi Kumar",
    date: "2025-05-20",
    brand: "Samsung",
    quantity: 2,
    amount: 48000,
    status: "Full-Paid",
    product: {
      id: "prd001",
      image: "/stock.png",
      name: "Galaxy A54",
      category: "Smartphone",
    },
    mobile: "9876543210",
    payment: "UPI",
    gstBill: true,
  },
  {
    id: 2,
    customer: "Anjali Mehta",
    date: "2025-05-18",
    brand: "Apple",
    quantity: 1,
    amount: 75000,
    status: "Credited",
    product: {
      id: "prd002",
      image: "/stock.png",
      name: "iPhone 14",
      category: "Smartphone",
    },
    mobile: "9123456780",
    payment: "Bank",
    gstBill: false,
  },
  {
    id: 3,
    customer: "Mohit Sharma",
    date: "2025-05-15",
    brand: "Sony",
    quantity: 3,
    amount: 36000,
    status: "Not-Paid",
    product: {
      id: "prd003",
      image: "/stock.png",
      name: "Sony WH-1000XM4",
      category: "Headphones",
    },
    mobile: "9812345678",
    payment: "Cash",
    gstBill: true,
  },
  {
    id: 4,
    customer: "Sneha Agarwal",
    date: "2025-05-10",
    brand: "HP",
    quantity: 1,
    amount: 65000,
    status: "Full-Paid",
    product: {
      id: "prd004",
      image: "/stock.png",
      name: "HP Pavilion 15",
      category: "Laptop",
    },
    mobile: "9988776655",
    payment: "UPI",
    gstBill: true,
  },
  {
    id: 5,
    customer: "Amit Joshi",
    date: "2025-05-08",
    brand: "Lenovo",
    quantity: 2,
    amount: 88000,
    status: "Credited",
    product: {
      id: "prd005",
      image: "/stock.png",
      name: "Lenovo ThinkPad X1",
      category: "Laptop",
    },
    mobile: "9001122334",
    payment: "Bank",
    gstBill: false,
  },
    {
    id: 6,
    customer: "Anjali Mehta",
    date: "2025-05-18",
    brand: "Apple",
    quantity: 1,
    amount: 75000,
    status: "Credited",
    product: {
      id: "prd002",
      image: "/stock.png",
      name: "iPhone 14",
      category: "Smartphone",
    },
    mobile: "9123456780",
    payment: "Bank",
    gstBill: false,
  },
];
